ALTER TABLE BOOKS
    ADD COLUMN BESTSELLER BOOLEAN DEFAULT 0;

SET SQL_SAFE_UPDATES = 0;

UPDATE BOOKS B
    JOIN (
    SELECT BOOK_ID
    FROM RENTS
    GROUP BY BOOK_ID
    HAVING COUNT(*) > 2
    ) R ON b.BOOK_ID = R.BOOK_ID
    SET B.BESTSELLER = TRUE;

SET SQL_SAFE_UPDATES = 1;

SELECT * FROM books;

DROP PROCEDURE IF EXISTS UpdateBestsellers;

DELIMITER $$

CREATE PROCEDURE UpdateBestsellers()
BEGIN
   DECLARE rentCount INT;
   DECLARE finished INT DEFAULT 0;
   DECLARE b_id INT;

   DECLARE book_cursor CURSOR FOR SELECT BOOK_ID FROM BOOKS;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET finished = 1;

OPEN book_cursor;

WHILE finished = 0 DO
      FETCH book_cursor INTO b_id;
      IF finished = 0 THEN
SELECT COUNT(*) FROM RENTS
WHERE BOOK_ID = b_id
    INTO rentCount;

IF rentCount > 2 THEN
UPDATE BOOKS SET BESTSELLER = TRUE WHERE BOOK_ID = b_id;
ELSE
UPDATE BOOKS SET BESTSELLER = FALSE WHERE BOOK_ID = b_id;
END IF;

COMMIT;
END IF;
END WHILE;

CLOSE book_cursor;
END $$

DELIMITER ;

CALL UpdateBestsellers();

SELECT * FROM books;