CREATE TABLE STATS (
                       STAT_ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
                       STAT_DATE DATETIME NOT NULL,
                       STAT VARCHAR(20) NOT NULL,
                       VALUE INT(11) NOT NULL
);

CREATE VIEW BESTSELLERS_COUNT AS
SELECT COUNT(*) AS COUNT_BESTSELLERS
FROM BOOKS
WHERE BESTSELLER = TRUE;

SET GLOBAL EVENT_SCHEDULER = ON;

DELIMITER $$

CREATE EVENT UPDATE_BESTSELLERS_STATS
ON SCHEDULE EVERY 1 MINUTE
DO
BEGIN
CALL UpdateBestsellers();

INSERT INTO STATS (STAT_DATE, STAT, VALUE)
SELECT CURTIME(), 'BESTSELLERS', COUNT_BESTSELLERS
FROM BESTSELLERS_COUNT;
END $$

DELIMITER ;

DROP EVENT UPDATE_BESTSELLERS_STATS;