EXPLAIN SELECT * FROM READERS WHERE FIRSTNAME = 'John';

CREATE INDEX INDEX_READERS_FIRSTNAME ON READERS(FIRSTNAME);
CREATE INDEX INDEX_READERS_LASTNAME ON READERS(LASTNAME);
CREATE INDEX INDEX_BOOKS_TITLE ON BOOKS(TITLE);

EXPLAIN SELECT * FROM READERS WHERE FIRSTNAME = 'John';
